name: Development Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Create Development Build
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Set version
      run: |
        GIT_COMMIT=$(git rev-parse --short HEAD)
        echo "VERSION=Dev-${GIT_COMMIT}" >> $GITHUB_ENV

    - name: Build and Package
      run: |
        make VERSION=${{ env.VERSION }} dmg

    - name: Verify Architecture Support
      run: |
        echo "Checking development version architecture compatibility..."
        make check-arch

    - name: Generate Release Notes
      id: release_notes
      run: |
        echo "### Update content" >> release_notes.md
        echo "- This is the latest development version build" >> release_notes.md
        echo "- Build Time: $(date '+%Y-%m-%d %H:%M:%S')" >> release_notes.md
        echo "- Supports Intel and Apple Silicon chips" >> release_notes.md

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: "Development"
        body_path: release_notes.md
        draft: false
        prerelease: true
        tag_name: "develop"
        files: |
          build/MacMusicPlayer-x86_64.dmg
          build/MacMusicPlayer-arm64.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}