name: Development Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Create Development Build
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Set version
      run: |
        GIT_COMMIT=$(git rev-parse --short HEAD)
        echo "VERSION=Dev-${GIT_COMMIT}" >> $GITHUB_ENV

    - name: Build and Package
      run: |
        make VERSION=${{ env.VERSION }} dmg

    - name: Generate Release Notes
      id: release_notes
      run: |
        echo "## MacMusicPlayer Development Build" > release_notes.md
        echo "" >> release_notes.md
        echo "### 更新内容" >> release_notes.md
        echo "- 这是最新的开发版本构建" >> release_notes.md
        echo "- 构建时间: $(date '+%Y-%m-%d %H:%M:%S')" >> release_notes.md

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: "Development Build (${{ env.VERSION }})"
        body_path: release_notes.md
        draft: false
        prerelease: true
        tag_name: "dev-${{ env.VERSION }}"
        files: |
          MacMusicPlayer-${{ env.VERSION }}.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}