name: Development Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Create Development Build
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Set version
      run: echo "VERSION=develop" >> $GITHUB_ENV

    - name: Build
      run: |
        xcodebuild clean archive -project MacMusicPlayer.xcodeproj \
          -scheme MacMusicPlayer \
          -archivePath ./build/MacMusicPlayer.xcarchive \
          CODE_SIGN_STYLE=Manual \
          CODE_SIGN_IDENTITY="-" \
          DEVELOPMENT_TEAM=""

    - name: Export App
      run: |
        xcodebuild -exportArchive \
          -archivePath ./build/MacMusicPlayer.xcarchive \
          -exportOptionsPlist exportOptions.plist \
          -exportPath ./build

    - name: Create DMG
      run: |
        # Create a temporary directory for mounting
        TEMP_DIR=$(mktemp -d)
        
        # Copy app to temp directory
        mkdir -p $TEMP_DIR
        cp -r "./build/MacMusicPlayer.app" "$TEMP_DIR/"
        
        # Create symbolic link to Applications folder
        ln -s /Applications "$TEMP_DIR/Applications"
        
        # Create a DMG
        hdiutil create -volname "MacMusicPlayer" -srcfolder "$TEMP_DIR" \
          -ov -format UDZO "MacMusicPlayer-${{ env.VERSION }}.dmg"
        
        # Clean up
        rm -rf "$TEMP_DIR"

    - name: Generate Release Notes
      id: release_notes
      run: |
        echo "## MacMusicPlayer Development Build" > release_notes.md
        echo "" >> release_notes.md
        echo "### 更新内容" >> release_notes.md
        echo "- 这是最新的开发版本构建" >> release_notes.md
        echo "- 构建时间: $(date '+%Y-%m-%d %H:%M:%S')" >> release_notes.md

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: MacMusicPlayer Development Build
        body_path: release_notes.md
        draft: false
        prerelease: true
        tag_name: develop
        files: |
          MacMusicPlayer-${{ env.VERSION }}.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}