name: Pull Request Test

on:
  pull_request:
    branches: ["main"]  # Listen for PRs targeting the main branch

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build
        run: |
          xcodebuild clean build \
            -project MacMusicPlayer.xcodeproj \
            -scheme MacMusicPlayer \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            ONLY_ACTIVE_ARCH=NO \
            ARCHS="x86_64 arm64"

      - name: Verify Architectures
        run: |
          # Find the path of the application.
          APP_PATH=$(find $PWD -name MacMusicPlayer.app -type d | head -n 1)
          echo "App Path: $APP_PATH"

          # Find the path of the executable file.
          EXECUTABLE_PATH="$APP_PATH/Contents/MacOS/MacMusicPlayer"
          echo "Executable Path: $EXECUTABLE_PATH"

          # Display the architecture information 
          lipo -info "$EXECUTABLE_PATH"
