name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Build
      run: |
        xcodebuild clean archive -project MacMusicPlayer.xcodeproj \
          -scheme MacMusicPlayer \
          -archivePath ./build/MacMusicPlayer.xcarchive \
          CODE_SIGN_STYLE=Manual \
          CODE_SIGN_IDENTITY="-" \
          DEVELOPMENT_TEAM=""

    - name: Export App
      run: |
        xcodebuild -exportArchive \
          -archivePath ./build/MacMusicPlayer.xcarchive \
          -exportOptionsPlist exportOptions.plist \
          -exportPath ./build

    - name: Create DMG
      run: |
        # Create a temporary directory for mounting
        TEMP_DIR=$(mktemp -d)
        
        # Copy app to temp directory
        mkdir -p $TEMP_DIR
        cp -r "./build/MacMusicPlayer.app" "$TEMP_DIR/"
        
        # Create symbolic link to Applications folder
        ln -s /Applications "$TEMP_DIR/Applications"
        
        # Create a DMG
        hdiutil create -volname "MacMusicPlayer" -srcfolder "$TEMP_DIR" \
          -ov -format UDZO "MacMusicPlayer-${{ env.VERSION }}.dmg"
        
        # Clean up
        rm -rf "$TEMP_DIR"

    - name: Generate Release Notes
      id: release_notes
      run: |
        echo "## MacMusicPlayer ${{ env.VERSION }}" > release_notes.md
        echo "" >> release_notes.md
        echo "### Update content" >> release_notes.md
        echo "- Please check the specific submission records for detailed update content." >> release_notes.md

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ env.VERSION }}
        body_path: release_notes.md
        draft: false
        prerelease: false
        files: |
          MacMusicPlayer-${{ env.VERSION }}.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Trigger Homebrew Update
      if: success()  # 只在前面的步骤都成功时才触发
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GH_PAT }}
        event-type: trigger-homebrew-update
        client-payload: '{"version": "${{ env.VERSION }}"}'

    - name: Update Latest Tag
      run: |
        git tag -f latest
        git push origin latest --force